export enum EventType {
    DATABASE_MODIFICATION,
    PURCHASE_ORDERS,
    RESERVATIONS,
    TRAINING,
    INVENTORY_MANAGEMENT,
    TRAINING_MANAGEMENT,
    EQUIPMENT_MANAGEMENT,
    USER_MANAGEMENT
}