@startuml

title Makerspace Portal Login Sequence

actor User
participant Frontend
participant Server
participant IDP as "Identity Provider (IDP)"
database Database

User -> Frontend : Go to Makerspace Portal
Frontend -> Server : Query signed-in user

alt User already signed in
    Server -->o Frontend : Signed-in user object
end

Server --> Frontend : ""null""
Frontend -> Server : Redirect browser to ""/login""
Server -> IDP : Redirect browser to\nSSO login page
User -> IDP : Sign in w/ RIT credentials
IDP -> Server : POST ""/login/callback""\nwith signed-in user stuff
Server -> Database : Query for user with matching RIT ID from IDP
Database --> Server : Makerspace user information
Server -> Server : Set user context for GraphQL
Server -> Frontend : Redirect browser to\nMakerspace Portal
Frontend -> Server : Query signed-in user
Server --> Frontend : Signed-in user object
Frontend -> Frontend : If user object is missing fields,\nredirect to first time user setup

@enduml
